version: '3.8'

services:
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: NyxBE
    volumes:
      - nyx-be:/var/lib/data
    env_file:
      - ".env"
    environment:
      - DB_HOST=db
      - root_data_folder=/var/lib/data
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    container_name: NyxDB
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - nyx-db:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      start_period: 10s
      interval: 15s
    ports:
      - "5432:5432"

volumes:
  nyx-db:
    driver: local
  nyx-be:
    driver: local
